In [1]:
import numpy as np 
from tensorflow.keras.datasets import mnist
(x_train,y_train),(x_test,y_test)=mnist.load_data()

In [2]:
num_labels=len(np.unique(y_train))
print(num_labels)

10


In [3]:
print("labels:tty{0}".format(np.unique(y_train)))

labels:tty[0 1 2 3 4 5 6 7 8 9]


In [4]:
from tensorflow.keras.utils import to_categorical
y_train=to_categorical(y_train)
y_test=to_categorical(y_test)

In [5]:
print(y_train,y_test)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]] [[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [6]:
img_siz=x_train.shape[1]
input_size=img_siz* img_siz

x_train=np.reshape(x_train,[-1,input_size])
x_train=x_train.astype('float32')/255

x_test =np.reshape(x_test,[-1,input_size])
x_test=x_train.astype('float32')/255

In [7]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Activation,Dropout 
batch_size=128
hidden_units=256
dropout=0.45

model=Sequential()
model.add(Dense(hidden_units,input_dim=input_size))
model.add(Activation('relu'))
model.add(Dropout(dropout))

model.add(Dense(hidden_units))
model.add(Activation('relu'))
model.add(Dropout(dropout))

model.add(Dense(num_labels))


In [8]:
model.add(Activation ('softmax'))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 256)               200960    
_________________________________________________________________
activation (Activation)      (None, 256)               0         
_________________________________________________________________
dropout (Dropout)            (None, 256)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 256)               65792     
_________________________________________________________________
activation_1 (Activation)    (None, 256)               0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 256)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 10)                2

In [9]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [10]:
model.fit(x_train,y_train,epochs=20,batch_size=batch_size)

Epoch 1/20
469/469 [==============================] - 3s 6ms/step - loss: 0.4214 - accuracy: 0.8704
Epoch 2/20
469/469 [==============================] - 3s 6ms/step - loss: 0.1933 - accuracy: 0.9417
Epoch 3/20
469/469 [==============================] - 2s 5ms/step - loss: 0.1491 - accuracy: 0.9552
Epoch 4/20
469/469 [==============================] - 2s 5ms/step - loss: 0.1280 - accuracy: 0.9618
Epoch 5/20
469/469 [==============================] - 2s 5ms/step - loss: 0.1130 - accuracy: 0.9661
Epoch 6/20
469/469 [==============================] - 2s 5ms/step - loss: 0.1027 - accuracy: 0.9682
Epoch 7/20
469/469 [==============================] - 2s 5ms/step - loss: 0.0919 - accuracy: 0.9716
Epoch 8/20
469/469 [==============================] - 2s 5ms/step - loss: 0.0901 - accuracy: 0.9712
Epoch 9/20
469/469 [==============================] - 2s 5ms/step - loss: 0.0798 - accuracy: 0.9749
Epoch 10/20
469/469 [==============================] - 2s 5ms/step - loss: 0.0756 - accuracy: 0.9754

In [15]:
_,acc= model.evaluate(x_test,y_test,batch_size=batch_size,verbose=0)
print("nAccuracy:%.1f%%n" % (100.0*acc))

ValueError: Data cardinality is ambiguous:
  x sizes: 60000
  y sizes: 10000
Please provide data which shares the same first dimension.